In [1]:
#import the packages
import pandas as mypd
from sklearn import svm
#two things-svc for classification & svr for regression
#For parameter optimization
from sklearn.model_selection import GridSearchCV

In [2]:
# Import the trainng data
mydata = mypd.read_csv("Iris_data.csv")

In [3]:
mydata.head()

   Unnamed: 0  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
0           1           5.1          3.5           1.4          0.2        0
1           2           4.9          3.0           1.4          0.2        0
2           3           4.7          3.2           1.3          0.2        0
3           4           4.6          3.1           1.5          0.2        0
4           5           5.0          3.6           1.4          0.2        0

In [4]:
# Seperate x's and y
x = mydata.iloc[:, 1:5]
y = mydata.Species

In [5]:
# Specify the model
mymodel = svm.SVC()

In [6]:
# Fit the model tot he data
mymodel = mymodel.fit(x,y)

In [7]:
# Set up the parameter grid
myparamgrid = [{'kernel' : ['linear', 'poly', 'rbf'], 'degree' : [1, 2, 3], 'C': [ 0.001, 0.01, 0.1, 1, 5, 10, 100]}]

In [8]:
# Set up the search
mysearch = GridSearchCV(mymodel, myparamgrid, scoring= 'accuracy', cv = 5, verbose= True)

In [9]:
# Fit the search to the data
mysearch = mysearch.fit(x,y)

Fitting 5 folds for each of 63 candidates, totalling 315 fits

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 315 out of 315 | elapsed:    1.6s finished

In [10]:
# Best parameters ofthe model
mysearch.best_params_

{'C': 1, 'degree': 2, 'kernel': 'poly'}

In [11]:
# Specify the optimum model
mymodel = svm.SVC(kernel= 'poly', degree= 2, C= 1, probability= True)

In [12]:
# Fit the optimum model
mymodel = mymodel.fit(x, y)

In [13]:
# Accuracy
accuracy = mymodel.score(x,y)
round(accuracy*100,2)

98.02

In [14]:
# Predicted values
predy = mymodel.predict(x)

In [15]:
# Actual versus Predicted values
mytable = mypd.crosstab(y, predy)
mytable

col_0     0   1   2
Species
0        34   0   0
1         0  35   1
2         0   1  30

In [17]:
# Import the test data
test = mypd.read_csv("Iris_test.csv")

In [18]:
# Explore the test data
test.head()

   Unnamed: 0  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
0           6           5.4          3.9           1.7          0.4        0
1           8           5.0          3.4           1.5          0.2        0
2          13           4.8          3.0           1.4          0.1        0
3          14           4.3          3.0           1.1          0.1        0
4          19           5.7          3.8           1.7          0.3        0

In [19]:
# Separate x's & y
testx = test.iloc[:, 1:5]
testy = test.Species

In [20]:
# Accuracy on test data
test_accuracy = mymodel.score(testx, testy)
round(test_accuracy*100,2)

93.88

In [21]:
# Predict the values for test data
predtest = mymodel.predict(testx)

In [22]:
# Actual versus predicted for test data
mytesttable = mypd.crosstab(testy, predtest)
mytesttable

col_0     0   1   2
Species
0        16   0   0
1         0  11   3
2         0   0  19

In [23]:
# Make predicted vlaues as a dataframe
predtest = mypd.DataFrame(predtest, columns= ["predicted"])

In [24]:
# predicted probabilities for test data
predprob = mymodel.predict_proba(testx)

In [25]:
# make predicted probabiliteis as dataframe
predprob = mypd.DataFrame(predprob, columns= ["Setosa", "Versicolor", "Virginica"])

In [ ]:
#OR
# make predicted probabiliteis as dataframe
#predprob = mypd.DataFrame(predprob, columns= ["prob 0", "prob 1", "prob 2"])

In [26]:
# Combine result with the test data
myresult = test.join(predtest)

In [27]:
myresult = myresult.join(predprob)

In [28]:
round(myresult,4)

,Unnamed: 0,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species,predicted,Setosa,Versicolor,Virginica
0,6,5.4,3.9,1.7,0.4,0,0,0.9369,0.0447,0.0184
1,8,5.0,3.4,1.5,0.2,0,0,0.9435,0.0388,0.0177
2,13,4.8,3.0,1.4,0.1,0,0,0.9403,0.0413,0.0184
3,14,4.3,3.0,1.1,0.1,0,0,0.9597,0.0250,0.0153
4,19,5.7,3.8,1.7,0.3,0,0,0.9334,0.0488,0.0178
5,24,5.1,3.3,1.7,0.5,0,0,0.8980,0.0773,0.0247
6,25,4.8,3.4,1.9,0.2,0,0,0.9034,0.0713,0.0254
7,26,5.0,3.0,1.6,0.2,0,0,0.9132,0.0644,0.0224
8,27,5.0,3.4,1.6,0.4,0,0,0.9251,0.0538,0.0211
9,28,5.2,3.5,1.5,0.2,0,0,0.9446,0.0386,0.0169
10,30,4.7,3.2,1.6,0.2,0,0,0.9283,0.0505,0.0212
11,31,4.8,3.1,1.6,0.2,0,0,0.9219,0.0562,0.0219
12,34,5.5,4.2,1.4,0.2,0,0,0.9730,0.0164,0.0106
13,40,5.1,3.4,1.5,0.2,0,0,0.9428,0.0397,0.0175
14,41,5.0,3.5,1.3,0.3,0,0,0.9565,0.0285,0.0150
15,50,5.0,3.3,1.4,0.2,0,0,0.9455,0.0375,0.0170
16,53,6.9,3.1,4.9,1.5,1,1,0.0097,0.6393,0.3510
17,55,6.5,2.8,4.6,1.5,1,1,0.0108,0.7797,0.2095
18,57,6.3,3.3,4.7,1.6,1,1,0.0121,0.7409,0.2469
19,59,6.6,2.9,4.6,1.3,1,1,0.0063,0.8875,0.1062
20,63,6.0,2.2,4.0,1.0,1,1,0.0093,0.9756,0.0151
21,66,6.7,3.1,4.4,1.4,1,1,0.0052,0.9359,0.0589
22,68,5.8,2.7,4.1,1.0,1,1,0.0120,0.9739,0.0141
23,73,6.3,2.5,4.9,1.5,1,2,0.0154,0.4603,0.5243
24,78,6.7,3.0,5.0,1.7,1,2,0.0135,0.3367,0.6499
25,84,6.0,2.7,5.1,1.6,1,2,0.0170,0.2572,0.7258
26,87,6.7,3.1,4.7,1.5,1,1,0.0095,0.7806,0.2099
27,88,6.3,2.3,4.4,1.3,1,1,0.0079,0.8878,0.1043
28,90,5.5,2.5,4.0,1.3,1,1,0.0147,0.9561,0.0292
29,93,5.8,2.6,4.0,1.2,1,1,0.0122,0.9684,0.0194
30,103,7.1,3.0,5.9,2.1,2,2,0.0021,0.0026,0.9953
31,104,6.3,2.9,5.6,1.8,2,2,0.0073,0.0277,0.9649
32,105,6.5,3.0,5.8,2.2,2,2,0.0033,0.0029,0.9938
33,106,7.6,3.0,6.6,2.1,2,2,0.0000,0.0000,1.0000
34,108,7.3,2.9,6.3,1.8,2,2,0.0010,0.0012,0.9977
35,110,7.2,3.6,6.1,2.5,2,2,0.0011,0.0004,0.9985
36,111,6.5,3.2,5.1,2.0,2,2,0.0135,0.1238,0.8627
37,113,6.8,3.0,5.5,2.1,2,2,0.0054,0.0150,0.9796
38,114,5.7,2.5,5.0,2.0,2,2,0.0196,0.1023,0.8780
39,115,5.8,2.8,5.1,2.4,2,2,0.0137,0.0248,0.9616
40,120,6.0,2.2,5.0,1.5,2,2,0.0178,0.3074,0.6748
41,128,6.1,3.0,4.9,1.8,2,2,0.0191,0.3322,0.6487
42,129,6.4,2.8,5.6,2.1,2,2,0.0052,0.0084,0.9863
43,130,7.2,3.0,5.8,1.6,2,2,0.0040,0.0282,0.9678
44,131,7.4,2.8,6.1,1.9,2,2,0.0013,0.0018,0.9968
45,136,7.7,3.0,6.1,2.3,2,2,0.0000,0.0000,1.0000
46,137,6.3,3.4,5.6,2.4,2,2,0.0050,0.0050,0.9899
47,140,6.9,3.1,5.4,2.1,2,2,0.0065,0.0251,0.9684
48,148,6.5,3.0,5.2,2.0,2,2,0.0112,0.0715,0.9172